### PR TITLE
pl/set search filter menu visible by default and have it persist across sessions

### PR DESCRIPTION
**Pull request by ParkerGits**
( #768 )
The filter is now open by default and the state of the filter is stored in localStorage so that it persists across sessions. Filter no longer toggles off on click away. 

searching

### CODE REVIEW

**Comment by ParkerGits** [comment]
filter

**Comment by joelhooks** [comment]
I feel pretty strongly that this bar needs to move below the topic page content if this is gonna be open by default because it is hideous.

**Comment by ParkerGits** [comment]
I moved the search bar below the topic page content, but felt unhappy about this functionality:
no scrollto

Setting the page to scroll to the top of the topic page content on query seems like a decent remedy:
with scrollto

Having to scroll to the bottom of, say, the React topic page content after searching "react" doesn't seem too bad. Could it be more clear that the search bar has moved down?

**Comment by joelhooks** [comment]
I think it's "kind of janky" but less so than having that dropdown open at the top of our lovely Topic Pages before the content.


What I'd love to see is the filters moved to a side column next to the search results while keeping the bar prominently up at the top of the page and "solid like granite" in terms of its positioning. Moving user inputs around after they finish typing "react" is not great!


Here's how it looks on egghead-rails:





Feels like we could get that simple layout done relatively quickly and maybe skip this decision about moving inputs around the page while opening up the filters so learners know they have that power without needing to dig into a buried UI.

**Comment by MaggieAppleton** [comment]
Making the filters always visible in a side column is definitely the next step. It requires a non-trivial redesign of the search page though.

Having the filter menu be open by default is not ideal, but it was meant as a temporary solution while we design and implement a more robust solution.

If we think having the topic menu open at the top of the page is too invasive, I vote we skip this temporary fix, and wait to fix the problem in a more cohesive way. I'm writing specs for a better solution today, and will have a pitch written up before Wednesday.

**Comment by dealingwith** [comment]
If we need to abandon this specific direction, this PR should be closed

**Comment by MaggieAppleton** [comment]
Yup – to follow up on this, we've decided to step back and holistically redesign the search functionality rather than implement a temporary patch to the filtering issue.

Thanks for working on this anyway @ParkerGits! Appreciate the effort. We'll make sure to get everyone on the same page before scoping out the next round of improvements to search.

**Pull request closed without merging**
