### PR TITLE
Add system preference default for dark mode

### PR DESCRIPTION
**Pull request by zacjones93**
- Checks system preferences on the machine and sets the default

https://user-images.githubusercontent.com/6188161/106482991-0a82d200-647c-11eb-8042-5d01735523a6.mp4

### CODE REVIEW

**Comment by zacjones93** [comment]
Ah, with the `<DarkModeToggle />` being re-mounted on page transitions this is jarring if you switch to the light/dark mode that isn't your system preference

**Comment by vojtaholik** [comment]
tailwind can check for this too https://tailwindcss.com/docs/dark-mode

**Comment by zacjones93** [comment]
@vojtaholik are there reasons why we don't do that? happy to put that PR in if you think it's an upgrade

**Comment by vojtaholik** [comment]
@zacjones93 currently it doesn't support combination of manual toggle and system preference at the same time and can only handle one of them. ;(

**Pull request closed without merging**
