### PR TITLE
AWS curated landing page

### PR DESCRIPTION
**Pull request by wjohnson85**
Curated AWS Landing page 

image

image

### CODE REVIEW

**Comment by zacjones93** [comment]
I updated the CTA to be the new AWS course.

In-Depth Up-to-Date AWS Tutorials for 2021  egghead io

**Comment by joelhooks** [comment]
looks good. imo this should respect light/dark mode

**Comment by zacjones93** [comment]
adjusted the svg to respect dark/light mode

In-Depth Up-to-Date AWS Tutorials for 2021  egghead io
In-Depth Up-to-Date AWS Tutorials for 2021  egghead io

**Comment by zacjones93** [comment]
Noticed a weird behavior on the aws page

https://www.loom.com/share/5f1b948c865c428497824db51af3e6af

**Comment by wjohnson85** [comment]
> Noticed a weird behavior on the aws page
> 
> 
> https://www.loom.com/share/5f1b948c865c428497824db51af3e6af

hey @zacjones93 I'm not able to re-create that error. I did a git pull on this branch and everything worked fine
https://www.loom.com/share/1e615000be6d4ccd9271ce0535d60fdf

**Comment by vojtaholik** [comment]
@zacjones93 @wjohnson85 this should fix the incorrect refinements count issue: https://github.com/eggheadio/egghead-next/pull/578
it isn't related to this PR

**Review by zacjones93 — APPROVED** [review]

**Pull request merged**
