### PR TITLE
Fix margin issue with affected instructor pages

### PR DESCRIPTION
**Pull request by Creeland**
The following instructor's pages had issues with their featured resources margin. This PR adjusts the margin. 
- Stephani Eckles
- Hiroko Nishimura
- Kristian Freeman

## Before 
image

## After 
image

### CODE REVIEW

**Comment by laurosilvacom** [comment]
Kent's page would also need the padding https://egghead.io/q/resources-by-kent-c-dodds should we consider adding a margin to the SearchInstructorEssential component vs. updating all individual instructor pages?

**Comment by NicollGuarnizo** [comment]
> Kent's page would also need the padding https://egghead.io/q/resources-by-kent-c-dodds should we consider adding a margin to the SearchInstructorEssential component vs. updating all individual instructor pages?

That's already done on this [PR] (https://github.com/eggheadio/egghead-next/pull/891) -- Here it's been fixed on `SearchInstructorEssential` which fixes almost every page with the problem. @laurosilvacom

**Comment by NicollGuarnizo** [comment]
> Kent's page would also need the padding https://egghead.io/q/resources-by-kent-c-dodds should we consider adding a margin to the SearchInstructorEssential component vs. updating all individual instructor pages?

That's already done on this [PR] (https://github.com/eggheadio/egghead-next/pull/891) -- Here it's been fixed on `SearchInstructorEssential` which fixes almost every page with the problem.  There are only two pages that for its own design needed fixed in their own page @laurosilvacom

**Comment by Creeland** [comment]
Resolved by #891

**Pull request closed without merging**
