### PR TITLE
Fixed styles on disabled button modals

### PR DESCRIPTION
**Pull request by MaggieAppleton**
Cleaned up the design and copywriting on the modals on our course page disabled buttons. Iteration on https://github.com/eggheadio/egghead-next/pull/864

@Creeland did a great job of hooking up all the functionality 👍 

I took another pass at the styles and copywriting to make them consistent across the modals, our standard login page, and our pricing page. As much as possible we should keep copywriting on buttons/forms, and styling on elements (bullet list icons, buttons, font sizes) consistent.

Also cleaned up some responsive styling details and dark mode accommodations

Course page modal and /pricing now match:

Screenshot - 2021-09-16 09 40 34

Course page modal and /login match:

Screenshot - 2021-09-16 09 40 59

### Copywriting notes

- Changed login form titles from "Sign in (or up)" to "Sign in or create a free account" for clarity
- Change login buttons to match titles
- Removed "Pro" from any mentions of "member". "Pro membership" is an old term from when we had free account, members, and PRO members. We now only have free accounts and members. So instead of "Become a Pro member", we should just say "become a member"
- Changed the label above some of the email address forms from "Your email:" to "Email address". Both of these work but we had a random mix of the two and should just pick one for consistency

### Responsive styling and dark mode previews

Screenshot - 2021-09-16 10 16 14
Screenshot - 2021-09-16 10 16 19
Screenshot - 2021-09-16 10 16 26
Screenshot - 2021-09-16 10 16 41
Screenshot - 2021-09-16 10 16 48
Screenshot - 2021-09-16 10 20 27
Screenshot - 2021-09-16 10 21 52

### CODE REVIEW

**Comment by Creeland** [comment]
These look good! 

I just wanted to mention that I didn't get to handling the various states of the login form. The `h2`s are hardcoded in `LoginForm` and the title of the dialog stays. I'm not sure if it's worth spending the time changing though.
image

**Comment by laurosilvacom** [comment]
aesthetics of how we strcuture the benefits is important here, especially if its leading to CTA 

before:


CleanShot 2021-09-16 at 11 14 11@2x

after

CleanShot 2021-09-16 at 11 20 45@2x
:

**Review by laurosilvacom — APPROVED** [review]

**Comment by MaggieAppleton** [comment]
@laurosilvacom Benefits restructure looks good. Thanks for refining that and reviewing 🙌

**Comment by MaggieAppleton** [comment]
@Creeland Re: States of the login form.

We should definitely look at improving that user flow and removing the hardcoded titles from the `<DialogButton>` component. Are you up for tackling that in another PR?

I'm happy to take a look at it early next week if you've already got a lot on your plate though. LMK

**Pull request merged**
