### PR TITLE
Timecodes for Transcript + UI tweaks on the Lesson page

### PR DESCRIPTION
**Pull request by DrShpongle**
Screen Recording 2020-11-10 at 07 27 59 PM

Note: I was forced to downgrade `react-markdown` from 5.0.2 --> 4.3.1, because I was not able to get `renderers` prop working. They have [braking changes](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#new-serializer-property-node) in version 5.x.x but even example from the docs didn't work for me (probably I did it wrong).

thanks @vojtaholik for the reference 🙌

### CODE REVIEW

**Comment by joelhooks** [comment]
I'm going to look at react-markdown.

**Comment by jh3y** [comment]
I approve based solely on the GIF usage for this one 😅

**Comment by joelhooks** [comment]
@DrShpongle I was able to get this to work: https://codesandbox.io/s/fast-pine-qkxi0?file=/src/App.tsx

```typescript
matches &&
        matches.forEach((match: any, i: number) => {
          result = result.replace(
            match,
            `[${match.replace("[", "").replace("]", "")}](${match
              .replace("[", "")
              .replace("]", "")})`
          );
          if (i === matches.length - 1) {
            setTranscript(result);
          }
        });
```

I updated the regex thing to create `[3:33](3:33)` and that was the big trick here. I *think* that the latest version uses markdown more correctly or follows a different spec/version? I don't have deep knowledge here.

and

```tsx
<Markdown
        children={transcript || ""}
        renderers={{ link: LinkReference }}
      />
```

Where I changed `linkReference` to `link`

**Comment by joelhooks** [comment]
I'd consider pulling the matcher out as a `util` and writing a unit test for it, if you're feeling adventurous :)

**Comment by DrShpongle** [comment]
Sure, will tackle it tomorrow. Thanks for the help!

**Review by joelhooks — APPROVED** [review]

**Pull request merged**
